paths:
  /productSupplierMap:
     post:
      security:
        - bearerAuth: []
      tags: 
        - ProductSupplierMap
      summary: Add new productSupplierMap.
      operationId: addNewProductSupplierMap
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/AddProductSupplierMapReqObj"
      responses:
        200:
          description: Add new productSupplierMap.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    exaple: 200
                  response:
                    type: String
                    example: success
                  msg:
                    type: String
                    example: ProductSupplierMap has been added.
                  mapId:
                    type: integer
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
     get:
      security:
        - bearerAuth: []
      summary: Find and retrive all productSupplierMap.
      operationId: fetchAllProductSupplierMap
      tags:
        - ProductSupplierMap
      parameters:
        - in: query
          name: include
          description: To fetch all the associations.
          required: false
          schema:
            type: string
            example: all
      responses:
        200:
          description: ProductSupplierMap-List
          content:
            application/json:
              schema:
                $ref: "#/definitions/ProductSupplierMapList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
  /productSupplierMap/{mapId}:
    get:
      security:
        - bearerAuth: []
      summary: Find and retrive specific productSupplierMap.
      operationId: fetchSpecificProductSupplierMaptData
      tags:
       - ProductSupplierMap
      parameters:
        - in: path
          name: mapId
          description: Map-ID to fetch specific productSupplierMap data with the associations.
          required: true
          schema:
            type: string
            example: 1
        - in: query
          name: include
          description: To fetch all the associations.
          required: false
          schema:
            type: string
            example: all
      responses:
        200:
          description: ProductSupplierMap-Data
          content:
            application/json:
              schema:
                $ref: "#/definitions/ProductSupplierMapData"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
    put:
      security:
        - bearerAuth: []
      tags:
        - ProductSupplierMap
      summary: Update an existing productSupplierMap data.
      operationId: updateProductSupplierMapData
      produces:
        - application/json
      parameters:
        - in: path
          name: mapId
          description: Map-ID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/AddProductSupplierMapReqObj"
      responses:
        200:
          description: Update productSupplierMap data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  response:
                    type: string
                    example: success
                  msg:
                    type: string
                    example: ProductSupplierMap data updated successfully. 
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
    delete:
      security:
        - bearerAuth: []
      tags:
       - ProductSupplierMap
      summary: Delete ProductSupplierMap Record.
      operationId: deleteProductSupplierMapRecord
      parameters:
        - in: path
          name: mapId
          description: ID_Map(mapId)
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Delete ProductSupplierMap Record.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/definitions/successRes"
                  - $ref: "#/definitions/invalidRes"
                  - $ref: "#/definitions/errorRes"
              examples:
                success:
                  summary: Example of successful response.
                  value:
                    status: 200
                    response: success
                    msg: ProductSupplierMap has been deleted successfully.
                invalidId:
                  summary: Example of invalid response.
                  value:
                    status: 401
                    response: validationerror
                    msg: Invalid operation.
                error:
                  summary: Example of error response.
                  value:
                    status: 400
                    responses: error
                    msg: Some thing went wrong.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
definitions:
  ProductSupplierMapData:
    type: object
    properties:
      status:
        type: integer
        example: 200
      response:
        type: string
        example: success
      ProductSupplierMap:
        type: object
        properties:
          mapId:
            type: integer
          avail:
            type: number
          productId:
            type: integer
          supplierId:
            type: integer
  AddProductSupplierMapReqObj:
    type: object
    properties:
          avail:
            type: number
          productId:
            type: integer
          supplierId:
            type: integer
  ProductSupplierMapObj:
    type: array
    items:
      type: object
      properties:
          mapId:
            type: integer
          avail:
            type: number
          productId:
            type: integer
          supplierId:
            type: integer
  ProductSupplierMapList:
    type: object
    properties:
      status:
        type: integer
        example: 200
      response:
        type: string
        example: success
      ProductSupplierMap:
        $ref: "#/definitions/ProductSupplierMapObj"
  Error:
    type: object
    required:
      - status
      - response
    properties:
      status:
        type: integer
        example: 400
      response:
        type: string
        example: error
      msg:
        type: string
        example: Some thing went wrong.
      error:
        type: object
        properties:
          name:
            type: string
          errors:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
  successRes:
    type: object
    required:
      - status
      - response
    properties:
      status:
        type: integer
        example: 200
      response:
        type: string
        example: success
      msg:
        type: string
        example: Product has been deleted successfully.
  invalidRes:
    type: object
    required:
      - status
      - response
    properties:
      status:
        type: integer
        example: 400
      response:
        type: string
        example: invailid
      msg:
        type: string
        example: Invailid AdvisorID.
  errorRes:
    type: object
    required:
      - status
      - response
    properties:
      status:
        type: integer
        example: 500
      response:
        type: string
        rxample: error
      msg:
        type: string
        example: Some thing went wrong.